//Connects a corner sticker to all stickers on the piece that it is on (in clockwise direction)
export const adjacentCornerStickers = {
    A: ['A', 'E', 'R'],
    B: ['B', 'Q', 'N'],
    C: ['C', 'M', 'J'],
    D: ['D', 'I', 'F'],
    E: ['E', 'R', 'A'],
    F: ['F', 'D', 'I'],
    G: ['G', 'L', 'U'],
    H: ['H', 'X', 'S'],
    I: ['I', 'F', 'D'],
    J: ['J', 'C', 'M'],
    K: ['K', 'P', 'V'],
    L: ['L', 'U', 'G'],
    M: ['M', 'J', 'C'],
    N: ['N', 'B', 'Q'],
    O: ['O', 'T', 'W'],
    P: ['P', 'V', 'K'],
    Q: ['Q', 'N', 'B'],
    R: ['R', 'A', 'E'],
    S: ['S', 'H', 'X'],
    T: ['T', 'W', 'O'],
    U: ['U', 'G', 'L'],
    V: ['V', 'K', 'P'],
    W: ['W', 'O', 'T'],
    X: ['X', 'S', 'H'],
}
//Connects a edge sticker to all stickers on the piece that it is on
export const adjacentEdgeStickers = {
    A: ['A', 'Q'],
    B: ['B', 'M'],
    C: ['C', 'I'],
    D: ['D', 'E'],
    E: ['E', 'D'],
    F: ['F', 'L'],
    G: ['G', 'X'],
    H: ['H', 'R'],
    I: ['I', 'C'],
    J: ['J', 'P'],
    K: ['K', 'U'],
    L: ['L', 'F'],
    M: ['M', 'B'],
    N: ['N', 'T'],
    O: ['O', 'V'],
    P: ['P', 'J'],
    Q: ['Q', 'A'],
    R: ['R', 'H'],
    S: ['S', 'W'],
    T: ['T', 'N'],
    U: ['U', 'K'],
    V: ['V', 'O'],
    W: ['W', 'S'],
    X: ['X', 'G'],
}
